"""Demo profiles so the deck is not empty on first launch."""

from __future__ import annotations

SEED_USERS: list[dict] = [
    {
        "email": "mira@wiring.demo",
        "name": "Мира",
        "age": 27,
        "city": "Белград",
        "gender": "woman",
        "looking_for": "everyone",
        "bio": "Аутистка с таблицей сенсорных лимитов. Не зови в бар, зови смотреть документалку про грибы и молчать рядом.",
        "photo": "portraits/p07.jpg",
        "neuro": ["asd", "anxiety"],
        "vibe": ["routines", "nonsmalltalk", "overstim", "prodx"],
    },
    {
        "email": "leo@wiring.demo",
        "name": "Лео",
        "age": 29,
        "city": "Берлин",
        "gender": "man",
        "looking_for": "women",
        "bio": "СДВГ, три недописанных романа и одна идеально организованная полка с винилом. Отвечаю либо за 4 секунды, либо через 11 дней.",
        "photo": "portraits/p03.jpg",
        "neuro": ["adhd", "rsd"],
        "vibe": ["hyperfix", "terminally-online", "latedx"],
    },
    {
        "email": "sasha@wiring.demo",
        "name": "Саша",
        "age": 24,
        "city": "Тбилиси",
        "gender": "nb",
        "looking_for": "everyone",
        "bio": "AuDHD. Могу три часа рассказывать про метрополитены. Местоимения they/он. Небольшой разговор меня выключает.",
        "photo": "portraits/p02.jpg",
        "neuro": ["audhd", "pda"],
        "vibe": ["infodump", "enby", "selfdx", "voicenotes"],
    },
    {
        "email": "nina@wiring.demo",
        "name": "Нина",
        "age": 31,
        "city": "Москва",
        "gender": "woman",
        "looking_for": "women",
        "bio": "ПРЛ в ремиссии, терапия два раза в неделю, книги вместо ночных спиралей. Ищу человека, который не пугается интенсивности.",
        "photo": "portraits/p01.jpg",
        "neuro": ["bpd", "cptsd"],
        "vibe": ["healing", "trauma-informed", "anxious-att", "prodx"],
    },
    {
        "email": "mark@wiring.demo",
        "name": "Марк",
        "age": 34,
        "city": "Подгорица",
        "gender": "man",
        "looking_for": "women",
        "bio": "Поздний диагноз ОКР. Готовлю одну и ту же пасту идеально. Если план на вечер ломается — пиши заранее, не сюрпризом у двери.",
        "photo": "portraits/p08.jpg",
        "neuro": ["ocd", "anxiety"],
        "vibe": ["routines", "softlaunch", "prodx"],
    },
    {
        "email": "kira@wiring.demo",
        "name": "Кира",
        "age": 23,
        "city": "Стамбул",
        "gender": "woman",
        "looking_for": "everyone",
        "bio": "Плёнка, коты, special interest — советские панельные дома. Self-dx ADHD, не спорь, если не врач.",
        "photo": "portraits/p09.jpg",
        "neuro": ["adhd", "hsp"],
        "vibe": ["selfdx", "neurospicy", "just-a-little", "hyperfix"],
    },
    {
        "email": "ilya@wiring.demo",
        "name": "Илья",
        "age": 26,
        "city": "Ереван",
        "gender": "man",
        "looking_for": "everyone",
        "bio": "Синтезаторы и биполярка. В мании пишу альбом, в депрессии слушаю его и плачу. Ищу стабильный якорь, не спасателя.",
        "photo": "portraits/p04.jpg",
        "neuro": ["bipolar", "depression"],
        "vibe": ["voicenotes", "healing", "prodx"],
    },
    {
        "email": "tess@wiring.demo",
        "name": "Тесс",
        "age": 25,
        "city": "Варшава",
        "gender": "nb",
        "looking_for": "friends",
        "bio": "Ace. Хочу параллельный плей, винил и человека, которому не надо объяснять, почему прикосновения — отдельный пункт в меню.",
        "photo": "portraits/p06.jpg",
        "neuro": ["asd", "hsp"],
        "vibe": ["ace", "parallel", "enby", "nonsmalltalk"],
    },
    {
        "email": "olya@wiring.demo",
        "name": "Оля",
        "age": 28,
        "city": "Киев",
        "gender": "woman",
        "looking_for": "men",
        "bio": "СДВГ + ПРЛ лайт. Голосовые по 12 минут, потом три дня тишины. Если пишешь «как дела» — я уже устала.",
        "photo": "portraits/p05.jpg",
        "neuro": ["adhd", "bpd"],
        "vibe": ["voicenotes", "disorg-att", "terminally-online"],
    },
    {
        "email": "demo@wiring.app",
        "name": "Демо",
        "age": 28,
        "city": "онлайн",
        "gender": "other",
        "looking_for": "everyone",
        "bio": "Служебный профиль, чтобы сразу свайпать. Поставь свои теги в профиле, если хочешь честный эксперимент.",
        "photo": "",
        "neuro": ["audhd"],
        "vibe": ["selfdx", "terminally-online"],
        "password": "demo",
        "is_demo": True,
    },
]
