"""Demo profiles so the deck is not empty on first launch."""

from __future__ import annotations

SEED_USERS: list[dict] = [
    {
        "email": "tima@wiring.demo",
        "name": "Тима",
        "age": 21,
        "city": "Нови-Сад",
        "gender": "man",
        "looking_for": "everyone",
        "intent": "dating",
        "job": "ночные плейлисты",
        "communication": "мемы ок, «как дела» — нет. могу пропасть на два дня, это не игра",
        "bio": "СДВГ и ванная как студия. Сигарета — ритуал, не характер. Если зовёшь гулять, скажи маршрут заранее, иначе мозг пишет 14 концовок.",
        "photo": "people/01.jpg",
        "neuro": ["adhd", "rsd"],
        "vibe": ["terminally-online", "softlaunch", "latedx"],
        "prompts": [
            {"id": "never", "answer": "«ты опять куришь» от человека, которого знаю три сообщения."},
            {"id": "sunday", "answer": "худи, очередь из сериалов, человек рядом который не заполняет тишину."},
            {"id": "text", "answer": "голосовые можно, но предупреди. стена текста в 2 ночи — тоже можно."},
        ],
    },
    {
        "email": "ren@wiring.demo",
        "name": "Рен",
        "age": 23,
        "city": "Берлин",
        "gender": "nb",
        "looking_for": "everyone",
        "intent": "dating",
        "job": "грим и ужастики",
        "communication": "they/она. лучше сразу про странное, чем small talk про погоду",
        "bio": "AuDHD. Грим — не косплей ради лайков, а способ выключить лицо. Ищу человека, которому ок, что часть меня живёт в хорроре.",
        "photo": "people/02.jpg",
        "neuro": ["audhd", "bpd"],
        "vibe": ["enby", "hyperfix", "selfdx", "nonsmalltalk"],
        "prompts": [
            {"id": "special", "answer": "практический грим: как сделать «труп» так, чтобы мама не вызвала скорую."},
            {"id": "mask", "answer": "когда можно не улыбаться и не объяснять, почему сегодня белое лицо."},
            {"id": "deal", "answer": "«это же просто макияж, будь нормальной»."},
        ],
    },
    {
        "email": "lera@wiring.demo",
        "name": "Лера",
        "age": 26,
        "city": "Вильнюс",
        "gender": "woman",
        "looking_for": "everyone",
        "intent": "relationship",
        "job": "поле и плёнка",
        "communication": "текст медленный, звонки — только если договорились. духи на свидании лучше не надо",
        "bio": "HSP + аутизм. Платья и лестницы из веток — не эстетика Pinterest, а способ не быть в городе. Не зови в клуб, зови молчать в траве.",
        "photo": "people/03.jpg",
        "neuro": ["asd", "hsp"],
        "vibe": ["overstim", "parallel", "nonsmalltalk", "prodx"],
        "prompts": [
            {"id": "sensory", "answer": "ветер ок, басы из колонки — нет. жемчуг ношу, потому что он тихий."},
            {"id": "date", "answer": "деревянная лестница, поле, никакого сюрприза «я уже еду»."},
            {"id": "green", "answer": "человек, который не пугается паузы и не заполняет её вопросами."},
        ],
    },
    {
        "email": "asya@wiring.demo",
        "name": "Ася",
        "age": 22,
        "city": "Варшава",
        "gender": "woman",
        "looking_for": "everyone",
        "intent": "chat",
        "job": "розовый свет",
        "communication": "ночью пишу быстрее. днём могу быть прочитано-игнор, это батарея",
        "bio": "СДВГ, парик и ультрафиолет. Септум не личность, но если начнёшь с «а настоящие ли волосы» — я уже устала. Ищу гиперакцент на двоих.",
        "photo": "people/04.jpg",
        "neuro": ["adhd", "anxiety"],
        "vibe": ["neurospicy", "terminally-online", "just-a-little", "voicenotes"],
        "prompts": [
            {"id": "obsessed", "answer": "как снимать лицо в одном фиолетовом источнике, чтобы не было «как в клубе»."},
            {"id": "never", "answer": "комменты про парик, «улыбнись» и «ты так странно смотришь»."},
            {"id": "text", "answer": "сразу мясо или мем. «привет, как день» оставляй себе."},
        ],
    },
    {
        "email": "masha@wiring.demo",
        "name": "Маша",
        "age": 20,
        "city": "Киев",
        "gender": "woman",
        "looking_for": "everyone",
        "intent": "friends",
        "job": "коты и наклейки",
        "communication": "лучше текст. голосовые — если руки в шерсти",
        "bio": "Аутизм, футболка с котом в наушниках — это не шутка, это документалка про меня. Ищу параллельный плей и человека, которому можно показать новую наклейку на чехле.",
        "photo": "people/05.jpg",
        "neuro": ["asd", "anxiety"],
        "vibe": ["parallel", "routines", "selfdx", "softlaunch"],
        "prompts": [
            {"id": "special", "answer": "чехлы, наклейки, коты которые орут как я в наушниках."},
            {"id": "parallel", "answer": "каждый в телефоне, иногда локтем. разговаривать не обязательно."},
            {"id": "sunday", "answer": "ванная, чистое полотенце, никто не спрашивает планы на вечер."},
        ],
    },
    {
        "email": "gor@wiring.demo",
        "name": "Гор",
        "age": 25,
        "city": "Тбилиси",
        "gender": "man",
        "looking_for": "women",
        "intent": "dating",
        "job": "свитера и золотой час",
        "communication": "отвечаю неровно. если пропал — не охладел, просто выпал из дня",
        "bio": "Депрессия + СДВГ. Сигарета на фото — не приглашение «бросить вместе». Ищу человека, с которым можно стоять у красной стены и не придумывать разговор.",
        "photo": "people/06.jpg",
        "neuro": ["depression", "adhd"],
        "vibe": ["healing", "avoidant-att", "latedx", "spoons"],
        "prompts": [
            {"id": "spoons", "answer": "на закате две. после людей — ноль. не надо это мотивировать."},
            {"id": "date", "answer": "улица, свет, одна сигарета на двоих максимум. бары пропускаем."},
            {"id": "green", "answer": "«ок, напиши когда вернёшься» без допроса где был."},
        ],
    },
    {
        "email": "nika@wiring.demo",
        "name": "Ника",
        "age": 23,
        "city": "Белград",
        "gender": "woman",
        "looking_for": "men",
        "intent": "dating",
        "job": "набережные на закате",
        "communication": "можно писать вечером. утром я ещё не человек",
        "bio": "СДВГ, город как stim. Джинсовка на плече — не «инстаграм», просто жарко и надо куда деть руки. Если свидание, то прогулка с понятным концом, не «посмотрим по настроению».",
        "photo": "people/07.jpg",
        "neuro": ["adhd", "hsp"],
        "vibe": ["hyperfix", "softlaunch", "terminally-online"],
        "prompts": [
            {"id": "date", "answer": "мост, закат, заранее сказано во сколько расходимся."},
            {"id": "sensory", "answer": "толпа на смотровой — на пять минут. потом нужен край, где меньше людей."},
            {"id": "never", "answer": "«ты такая лёгкая, давай ещё бар»."},
        ],
    },
    {
        "email": "fedya@wiring.demo",
        "name": "Федя",
        "age": 21,
        "city": "Москва",
        "gender": "man",
        "looking_for": "everyone",
        "intent": "chat",
        "job": "маски и рутина",
        "communication": "текст. селфи с маской — это special interest, не фитнес-блог",
        "bio": "ОКР-лайт и тревожка. Уход за кожей — ритуал, который держит день. Можно ржать, нельзя говорить «ну ты девочка». Ищу человека, которому ок странные ритуалы.",
        "photo": "people/08.jpg",
        "neuro": ["ocd", "anxiety"],
        "vibe": ["routines", "selfdx", "healing", "nonsmalltalk"],
        "prompts": [
            {"id": "special", "answer": "кислоты, тканевые маски, почему нельзя пропускать вторник."},
            {"id": "never", "answer": "шутки про «ты как девчонка» и советы «просто не думай»."},
            {"id": "sunday", "answer": "маска, сериал без сюрпризов, никто не зовёт «на людей»."},
        ],
    },
    {
        "email": "sonya@wiring.demo",
        "name": "Соня",
        "age": 22,
        "city": "Краков",
        "gender": "woman",
        "looking_for": "everyone",
        "intent": "relationship",
        "job": "кровать как штаб",
        "communication": "долго читаю. если не ответила — не обиделась, собираю ложки",
        "bio": "Депрессия и HSP. Фото из комнаты, потому что мир снаружи часто слишком громкий. Ищу человека, которому можно написать «сегодня только плед» и получить «ок».",
        "photo": "people/09.jpg",
        "neuro": ["depression", "hsp"],
        "vibe": ["spoons", "anxious-att", "healing", "softlaunch"],
        "prompts": [
            {"id": "spoons", "answer": "утро — одна. вечер — если повезло. свидание только из третьей."},
            {"id": "text", "answer": "короткие факты. не читай паузу как «всё плохо»."},
            {"id": "deal", "answer": "«возьми себя в руки» и внезапные звонки."},
        ],
    },
    {
        "email": "zhenya@wiring.demo",
        "name": "Женя",
        "age": 24,
        "city": "Стамбул",
        "gender": "nb",
        "looking_for": "everyone",
        "intent": "dating",
        "job": "аниме и витрины",
        "communication": "they/он. наушники почти всегда. лучше написать, чем окликать в магазине",
        "bio": "СДВГ, тату как карта special interest. Красные очки — сенсорный фильтр, не поза. Если узнаёшь персонажа на футболке — нам уже есть о чём молчать рядом.",
        "photo": "people/10.jpg",
        "neuro": ["adhd", "asd"],
        "vibe": ["enby", "infodump", "terminally-online", "selfdx"],
        "prompts": [
            {"id": "obsessed", "answer": "шоппинг как stim: ткани, свет, не люди. и ещё один персонаж на руку."},
            {"id": "sensory", "answer": "очки с красными стёклами. люминесцентные лампы магазинов иначе режут."},
            {"id": "parallel", "answer": "ходить по вешалкам порознь, потом сравнить добычу."},
        ],
    },
    {
        "email": "eli@wiring.demo",
        "name": "Эли",
        "age": 22,
        "city": "Ереван",
        "gender": "man",
        "looking_for": "everyone",
        "intent": "dating",
        "job": "рога и чокеры",
        "communication": "можно странно. нельзя «ты гей или просто стиль»",
        "bio": "Аутизм, готика как скрипт, а не «фаза». Рога снимаются, проводка — нет. Ищу человека, которому не надо переводить образ на нормальный.",
        "photo": "people/11.jpg",
        "neuro": ["asd", "rsd"],
        "vibe": ["just-a-little", "nonsmalltalk", "masking", "selfdx"],
        "prompts": [
            {"id": "mask", "answer": "когда можно быть с рогами и без объяснения «это на тусовку»."},
            {"id": "never", "answer": "фетиш-допрос от незнакомца и шутки про «козлика»."},
            {"id": "green", "answer": "«крутой ободок» и смена темы. без анализа моей сексуальности."},
        ],
    },
    {
        "email": "danya@wiring.demo",
        "name": "Даня",
        "age": 23,
        "city": "Львов",
        "gender": "man",
        "looking_for": "everyone",
        "intent": "relationship",
        "job": "корги и снег",
        "communication": "лучше текст или голос про собак. small talk про работу пропускаем",
        "bio": "Аутизм. Два корги — не проп, а расписание дня. Если не любишь собак, мы не срастёмся. Если любишь — можно не разговаривать, они заведут беседу сами.",
        "photo": "people/12.jpg",
        "neuro": ["asd", "hsp"],
        "vibe": ["routines", "parallel", "trauma-informed", "prodx"],
        "prompts": [
            {"id": "special", "answer": "корги, зимний свет, почему щенки лучше людей в очереди."},
            {"id": "date", "answer": "прогулка по снегу, две собаки, заранее сказанный маршрут домой."},
            {"id": "deal", "answer": "«это же просто псы» и просьба оставить их одним «ненадолго»."},
        ],
    },
    {
        "email": "demo@wiring.app",
        "name": "Демо",
        "age": 28,
        "city": "онлайн / не важно",
        "gender": "other",
        "looking_for": "everyone",
        "intent": "chat",
        "job": "",
        "communication": "",
        "bio": "Служебный профиль для входа без регистрации.",
        "photo": "",
        "neuro": ["audhd"],
        "vibe": ["selfdx", "terminally-online"],
        "password": "demo",
        "is_demo": True,
    },
]
